server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_emsp?useSSL=false&serverTimezone=UTC
    username: root
    password: lxr123$!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      insert-strategy: ignored
      update-strategy: ignored
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL
  type-aliases-package: com.volvo.*.entity;
  mapper-locations:
    - classpath*:com/**/mapper/**/*Mapper.xml

cloud:
  nacos:
    discovery:
      server-addr: localhost:8848  # Nacos 本地开发环境
      service: account-service
      metadata:
        version: 1.0.1  # 开发环境服务版本

logging:
  level:
    org.springframework.web: INFO  # 开发环境日志级别设置为 INFO
    com.volvo.accountservice: DEBUG  # 开发环境开启 DEBUG 级别的日志
  file:
    name: account-service-dev.log  # 开发环境日志文件名

