server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_emsp?useSSL=false&serverTimezone=UTC
    username: root
    password: lxr123$!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境可自动更新数据库表结构
    database-platform: org.hibernate.dialect.MySQL5Dialect  # 数据库方言
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml  # MyBatis 的 XML 映射文件路径
    type-aliases-package: com.volvo.accountservice.entity  # 指定实体类包路径
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL

cloud:
  nacos:
    discovery:
      server-addr: localhost:8848  # Nacos 本地开发环境
      service: account-service-dev
      metadata:
        version: 1.0.0  # 开发环境服务版本

logging:
  level:
    org.springframework.web: INFO  # 开发环境日志级别设置为 INFO
    com.volvo.accountservice: DEBUG  # 开发环境开启 DEBUG 级别的日志
  file:
    name: account-service-dev.log  # 开发环境日志文件名

