server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${APPLICATION_NAME:account-service}
  profiles:
    active: ${PROFILES_ACTIVE:nacos}
  main:
    #该配置放在bootstrap中，在使用nacos的情况下会报错
    allow-circular-references: true
    allow-bean-definition-overriding: true
    servlet:
      multipart:
        #启用分段上传支持
        enabled: true
        #文件上传限制大小
        max-file-size: 150MB
        #请求数据限制大小
        max-request-size: 150MB
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        service: account-service
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:emsp}
        group: ${NACOS_GROUP:dev}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:emsp}
        group: ${NACOS_GROUP:dev}
        refreshable: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
