server:
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: ${APPLICATION_NAME:gateway-service}
  profiles:
    active: ${PROFILES_ACTIVE:nacos}
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:emsp}
        group: ${NACOS_GROUP:dev}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:emsp}
        group: ${NACOS_GROUP:dev}
        refreshable: true
        file-extension: yaml
